// src/helpers/data.ts

export const depositos = [
    // Dados do usuário com id: 1 (Gabriel Campos)
    {
        id: 1,
        userId: 1, // ID do usuário
        nome: 'Gabriel Campos',
        valorDepositado: 2000.00, // Valor depositado
        saldoAtual: 10000.00, // Saldo atual após o depósito
        status: 'Aprovado', // Status da transação
        dataDeposito: '2024-09-27', // Data do depósito
        comprovante: 'comprovante_deposito_2000.pdf', // Comprovante do depósito
        ultimaAtualizacao: '2024-09-27', // Última atualização
        observacoes: '', // Observações
    },
    {
        id: 2,
        userId: 1,
        nome: 'Gabriel Campos',
        valorDepositado: 5000.00,
        saldoAtual: 15000.00,
        status: 'Pendente',
        dataDeposito: '2024-09-25',
        comprovante: '',
        ultimaAtualizacao: '2024-09-25',
        observacoes: '',
    },
    {
        id: 3,
        userId: 1,
        nome: 'Gabriel Campos',
        valorDepositado: 1000.00,
        saldoAtual: 16000.00,
        status: 'Aprovado',
        dataDeposito: '2024-09-22',
        comprovante: 'comprovante_deposito_1000.pdf',
        ultimaAtualizacao: '2024-09-23',
        observacoes: '',
    },
    {
        id: 4,
        userId: 1,
        nome: 'Gabriel Campos',
        valorDepositado: 750.00,
        saldoAtual: 16750.00,
        status: 'Cancelado',
        dataDeposito: '2024-09-20',
        comprovante: '',
        ultimaAtualizacao: '2024-09-21',
        observacoes: 'Depósito cancelado pelo usuário.',
    },
    {
        id: 5,
        userId: 1,
        nome: 'Gabriel Campos',
        valorDepositado: 3000.00,
        saldoAtual: 19750.00,
        status: 'Aprovado',
        dataDeposito: '2024-09-18',
        comprovante: 'comprovante_deposito_3000.pdf',
        ultimaAtualizacao: '2024-09-19',
        observacoes: '',
    },

    // Dados do usuário com id: 2 (Ana Silva)
    {
        id: 6,
        userId: 2,
        nome: 'Ana Silva',
        valorDepositado: 1500.00,
        saldoAtual: 7000.00,
        status: 'Aprovado',
        dataDeposito: '2024-09-17',
        comprovante: 'comprovante_deposito_1500.pdf',
        ultimaAtualizacao: '2024-09-18',
        observacoes: '',
    },
    {
        id: 7,
        userId: 2,
        nome: 'Ana Silva',
        valorDepositado: 1000.00,
        saldoAtual: 8000.00,
        status: 'Pendente',
        dataDeposito: '2024-09-15',
        comprovante: '',
        ultimaAtualizacao: '2024-09-15',
        observacoes: '',
    },
    {
        id: 8,
        userId: 2,
        nome: 'Ana Silva',
        valorDepositado: 500.00,
        saldoAtual: 8500.00,
        status: 'Aprovado',
        dataDeposito: '2024-09-14',
        comprovante: 'comprovante_deposito_500.pdf',
        ultimaAtualizacao: '2024-09-15',
        observacoes: '',
    },
    {
        id: 9,
        userId: 2,
        nome: 'Ana Silva',
        valorDepositado: 2000.00,
        saldoAtual: 10500.00,
        status: 'Cancelado',
        dataDeposito: '2024-09-12',
        comprovante: '',
        ultimaAtualizacao: '2024-09-13',
        observacoes: 'Depósito cancelado pelo usuário.',
    },
    {
        id: 10,
        userId: 2,
        nome: 'Ana Silva',
        valorDepositado: 3000.00,
        saldoAtual: 13500.00,
        status: 'Aprovado',
        dataDeposito: '2024-09-10',
        comprovante: 'comprovante_deposito_3000.pdf',
        ultimaAtualizacao: '2024-09-11',
        observacoes: '',
    },
];


export const retiradas = [
    // Dados do usuário com id: 1 (Gabriel Campos)
    {
        id: 1,
        userId: 1, // ID do usuário
        nome: 'Gabriel Campos',
        valorSolicitado: 1500.00, // Valor solicitado para retirada
        valorDisponivel: 10000.00, // Valor disponível para retirada no momento da solicitação
        status: 'Pendente', // Status da solicitação
        dataSolicitacao: '2024-09-27', // Data da solicitação
        metodoPagamento: 'chavepix@gabriel.com', // Chave Pix usada para o pagamento
        comprovante: '', // Nenhum comprovante ainda, já que está pendente
        ultimaAtualizacao: '2024-09-27', // Última atualização da solicitação
        observacoes: '', // Observações (vazio por enquanto)
    },
    {
        id: 2,
        userId: 1,
        nome: 'Gabriel Campos',
        valorSolicitado: 2000.00,
        valorDisponivel: 8500.00,
        status: 'Aprovado',
        dataSolicitacao: '2024-09-20',
        metodoPagamento: 'chavepix@gabriel.com',
        comprovante: 'comprovante_2000.pdf',
        ultimaAtualizacao: '2024-09-22',
        observacoes: '',
    },
    {
        id: 3,
        userId: 1,
        nome: 'Gabriel Campos',
        valorSolicitado: 3000.00,
        valorDisponivel: 12000.00,
        status: 'Cancelado',
        dataSolicitacao: '2024-09-10',
        metodoPagamento: 'chavepix@gabriel.com',
        comprovante: '',
        ultimaAtualizacao: '2024-09-11',
        observacoes: 'Solicitação cancelada pelo usuário.',
    },
    {
        id: 4,
        userId: 1,
        nome: 'Gabriel Campos',
        valorSolicitado: 2500.00,
        valorDisponivel: 9200.00,
        status: 'Pendente',
        dataSolicitacao: '2024-09-25',
        metodoPagamento: 'chavepix@gabriel.com',
        comprovante: '',
        ultimaAtualizacao: '2024-09-25',
        observacoes: '',
    },
    {
        id: 5,
        userId: 1,
        nome: 'Gabriel Campos',
        valorSolicitado: 5000.00,
        valorDisponivel: 15000.00,
        status: 'Aprovado',
        dataSolicitacao: '2024-09-12',
        metodoPagamento: 'chavepix@gabriel.com',
        comprovante: 'comprovante_5000.pdf',
        ultimaAtualizacao: '2024-09-13',
        observacoes: '',
    },

    // Dados do usuário com id: 2 (Ana Silva)
    {
        id: 6,
        userId: 2,
        nome: 'Ana Silva',
        valorSolicitado: 1000.00,
        valorDisponivel: 5000.00,
        status: 'Pendente',
        dataSolicitacao: '2024-09-15',
        metodoPagamento: 'chavepix@ana.com',
        comprovante: '',
        ultimaAtualizacao: '2024-09-15',
        observacoes: '',
    },
    {
        id: 7,
        userId: 2,
        nome: 'Ana Silva',
        valorSolicitado: 1200.00,
        valorDisponivel: 8200.00,
        status: 'Aprovado',
        dataSolicitacao: '2024-09-18',
        metodoPagamento: 'chavepix@ana.com',
        comprovante: 'comprovante_1200.pdf',
        ultimaAtualizacao: '2024-09-19',
        observacoes: '',
    },
    {
        id: 8,
        userId: 2,
        nome: 'Ana Silva',
        valorSolicitado: 750.00,
        valorDisponivel: 3200.00,
        status: 'Cancelado',
        dataSolicitacao: '2024-09-16',
        metodoPagamento: 'chavepix@ana.com',
        comprovante: '',
        ultimaAtualizacao: '2024-09-17',
        observacoes: 'Solicitação foi rejeitada pelo sistema.',
    },
    {
        id: 9,
        userId: 2,
        nome: 'Ana Silva',
        valorSolicitado: 1800.00,
        valorDisponivel: 9200.00,
        status: 'Pendente',
        dataSolicitacao: '2024-09-20',
        metodoPagamento: 'chavepix@ana.com',
        comprovante: '',
        ultimaAtualizacao: '2024-09-20',
        observacoes: '',
    },
    {
        id: 10,
        userId: 2,
        nome: 'Ana Silva',
        valorSolicitado: 1500.00,
        valorDisponivel: 7000.00,
        status: 'Aprovado',
        dataSolicitacao: '2024-09-22',
        metodoPagamento: 'chavepix@ana.com',
        comprovante: 'comprovante_1500.pdf',
        ultimaAtualizacao: '2024-09-23',
        observacoes: '',
    },
];

